[package]
name = "squitterator"
version = "0.3.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.23", features = ["derive"] }
env_logger = "0.11.5"
lazy_static = "1.5.0"
log = "0.4.22"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
