name: CI

on:
  push:
    branches-ignore: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_and_test:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: actions-rust-lang/setup-rust-toolchain@v1
        - run: |    
            make lint
            make test
    